### ISSUE TITLE
"Create New Poll" suggestion

### ISSUE THREAD

**Issue by Ichi1234** [Pawat-Sarnchawanakit/ku-polls#26]
Should the same user create the same poll title and choice twice?

Is it okay if the user does not answer the "What is your name?" question in an "example survey" (user-created question)? (See the photo at #21 name: "blank" count: 1)

Can the user set the end date of the user-created polls? (relate to #25  issue)

**Comment by Pawat-Sarnchawanakit** [comment]
If required is not set to true, the user may leave the answer blank.
However, it seems this only applies to choices. I will write a fix to this.
How to set end date is specified in the template.
![image](https://github.com/user-attachments/assets/893dfc3a-de54-442b-b28a-5d272f3801fa)  
I will add a button to get the template back since your edit is saved locally to prevent information lost.
